### ISSUE TITLE
Why is ppc64le disabled?

### ISSUE THREAD

**Issue by photex** [conda-forge/pcl-feedstock#24]
Is there a specific technical reason for not enabling ppc64le for this feedstock?

Thanks!

**Comment by Tobias-Fischer** [comment]
Judging that a build on Linux takes >1.5 hours, my best guess is that the PPC build simply times out .. do you have a PPC machine available and could build this locally @photex?

**Comment by photex** [comment]
I had access briefly (mostly to evaluate whether we had various dependencies that we needed for the architecture). Currently though I do not.
But, build time outs are a perfectly reasonable explanation. :D Thanks!
