### ISSUE TITLE
Could you give some tutorials about how to use this

### ISSUE THREAD

**Issue by HanFengLiuuu** [conda-forge/pcl-feedstock#47]
### Comment:

Hello, it is my first time to use conda-forge, and I notice I could't `import pcl` in my python script after I install it.
And I check out the env folder where it was installed, I found  files about `pcl` just in those folders `bin, include, and share` not in `site-packages`.
So, I think this is the reason why I could not import it.
Could you give some tutorials about how to use this, Thanks!

**Comment by traversaro** [comment]
Hello @HanFengLiuuu, the `pcl` package is a C++ library and not a Python one, and you can find tutorial for its use in https://pcl.readthedocs.io/projects/tutorials/en/pcl-1.13.0/ . As far as I know, pcl does not provide any official Python bindings, see https://github.com/PointCloudLibrary/pcl/issues/5297 and https://github.com/PointCloudLibrary/pcl/issues/5472 .
