### ISSUE TITLE
PCL 0.14.0 missing for windows

### ISSUE THREAD

**Issue by traversaro** [conda-forge/pcl-feedstock#61]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

There was a post merge build: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=852572&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=6119ccbe-9301-594f-7c27-f792b80a7fcc

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by traversaro** [comment]
fyi @Tobias-Fischer

**Comment by Tobias-Fischer** [comment]
Started a rerun, thanks for reporting!

**Comment by Tobias-Fischer** [comment]
All fixed
